---
# This ansible cookbook will setup full routerstack which consist of:
# Base ubuntu installer: 
# Software Install: ISC-DHCP-Server, Bind9, FirewallD, NTPD, Vlan, bridge-utils, Wireguard, Cockpit, Nano, neofetch, unattended-upgrades
# Software removal: UFW
# Setup Network: Netplan
# Setup Kea-dhcp4
# Setup FirewallD + Vlans
# Setup Chronyd
# Setup Bind9 DNS


- hosts: 10.0.77.20
  become: yes
  become_method: sudo
  tasks:

    - name: Disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Disable Kea DHCP
      ansible.builtin.service:
        name: kea-dhcp4-server
        state: stopped
        enabled: false

    - name: Disable Kea DHCP6
      ansible.builtin.service:
        name: kea-dhcp6-server
        state: stopped
        enabled: false

      - name: Disable chronyd
        ansible.builtin.service:
          name: chronyd
          state: stopped
          enabled: false     
  roles:

    - delete-confs