---
#- Install applications needed for router
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - vlan
    - bridge-utils
    - firewalld
    - kea
    - chrony
    - bind9
    - wireguard
    - unattended-upgrades
    - cockpit
    - nano
    - wireguard
    - qrencode
    - neofetch
    - traceroute
    - openvswitch-switch-dpdk
    - network-manager

- name: Remove UFW
  ansible.builtin.apt:
    name: ufw
    state: absent