---
- name: write kea-dhcp.conf config using jinja2
  ansible.builtin.template:
   backup: true
   mode: 0644
   owner: root
   group: root
   src: kea-dhcp4.multi2.conf.j2
   dest: /etc/kea/kea-dhcp4.conf

# Restart service kera-dhcp4-server
- name: Enable kea-dhcp4-server
  ansible.builtin.service:
   name: kea-dhcp4-server
   state: restarted
   enabled: true