---
# Tweak Kernel parametes for network forwarding and activate VLAN
- name: Enabling routing in sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"

- name: Disable ipv6 routing in sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv6.conf.all.disable_ipv6 = 1"

- name: Disable ipv6 in sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv6.conf.default.disable_ipv6 = 1"
 
- name: enable vlan kernal module
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "8021q"



# Netplan install
- name: write netplan config using jinja2
  ansible.builtin.template:
    backup: true
    mode: 0600
    owner: root
    group: root
    src: netplan-00-installer-config2.j2
    dest: /etc/netplan/00-installer-config.yaml

# Restart netplan
- name: restart netplan
  command: sudo netplan apply

